version: "3"

services:

  fess01:
    image: flaviostutz/fess:13.5.2
    ports:
      - 8080:8080
    environment:
      - "ES_HTTP_URL=http://es01:9200"

  es01:
    build: .
    image: flaviostutz/fess-elasticsearch:7.5.1
    environment:
      - node.name=es01
      # - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01
      - cluster.name=fess-es
      - bootstrap.memory_lock=false
    # volumes:
    #   - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
